[profile.default]
solc_version = '0.8.17'
optimizer = true
optimizer_runs = 1000000
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
